name       : thin-provisioning-tools
version    : 1.0.6
release    : 3
source     :
    - https://github.com/jthornber/thin-provisioning-tools/archive/refs/tags/v1.0.6.tar.gz : bb64481c2bef330004b12cdae7cdc68a4790e55e4c0b7a3061dfb718e8396962
license    : GPL-3.0-or-later
component  : system.utils
summary    : A suite of tools for manipulating the metadata of the dm-thin, dm-cache and dm-era device-mapper targets
description: |
    A suite of tools for manipulating the metadata of the dm-thin, dm-cache and dm-era device-mapper targets.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    %make_install
