name       : thin-provisioning-tools
version    : 0.7.6
release    : 2
source     :
    - https://github.com/jthornber/thin-provisioning-tools/archive/v0.7.6.tar.gz : 491358c1406414ab3f06b260bd9da8a2f9109c4c426dda899d4d985860dfc01f
license    : GPL-3.0-or-later
component  : system.utils
summary    : A suite of tools for manipulating the metadata of the dm-thin, dm-cache and dm-era device-mapper targets
description: |
    A suite of tools for manipulating the metadata of the dm-thin, dm-cache and dm-era device-mapper targets.
builddeps  :
    - libaio-devel
    - libboost-devel
setup      : |
    %reconfigure --enable-testing
build      : |
    %make
install    : |
    %make_install
